[package]
name = "coal-program"
description = "COAL is a fair-launch, proof-of-work, digital currency everyone can mine"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "coal"

[features]
no-entrypoint = []
default = []

[dependencies]
drillx.workspace = true
mpl-token-metadata.workspace = true
coal-api.workspace = true
coal-utils.workspace = true
solana-program.workspace = true
spl-token.workspace = true
spl-associated-token-account.workspace = true

[dev-dependencies]
rand = "0.8.5"
